In [1]:
import numpy as np

#### Задание 1
Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

In [2]:
def can_dot(A, B):
    return (np.shape(A)[0], np.shape(B)[1]) if np.shape(A)[1] == np.shape(B)[0] else False

In [3]:
#a
print('a', can_dot(np.ones([4, 2]), np.ones([4, 2])))
#б
print('б', can_dot(np.ones([2, 5]), np.ones([5, 3])))
#в
print('в', can_dot(np.ones([8, 3]), np.ones([3, 8])))
#г
print('г', can_dot(np.ones([4, 4]), np.ones([4, 4])))

a False
б (2, 3)
в (8, 8)
г (4, 4)


#### Задание 2
Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [4]:
def dot(A, B):
    if not can_dot(A, B):
        raise Exception("Cant multiply matrixes with shapes", np.shape(A), np.shape(B))
        
    cols, count = np.shape(A)
    rows = np.shape(B)[1]
    C = np.zeros([cols, rows])
    for i in range(cols):
        for j in range(rows):
            C[i][j] = sum([A[i][p]*B[p][j] for p in range(count)])
    return C, (cols, rows)

In [5]:
def can_sum(A, B):
    return np.shape(A) == np.shape(B)

In [6]:
def m_sum(A, B):
    if not can_sum(A, B):
        raise Exception("Cant summirize matrixes with different shapes", np.shape(A), np.shape(B))
        
    (rows, cols) = np.shape(A)
    C = np.zeros([rows, cols])
    for row in range(rows):
        for col in range(cols):
            C[row][col] = A[row][col] + B[row][col]
    return C, (cols, rows)

In [7]:
A = [[1, -2], [0, 3]]
B = [[4, -1], [0, 5]]

S, s_shape = m_sum(A, B)
M, m_shape = dot(A, B)

print('SUM:')
print(S, s_shape)
print(np.add(A, B))
print('DOT:')
print(M, m_shape)
print(np.dot(A, B))

SUM:
[[ 5. -3.]
 [ 0.  8.]] (2, 2)
[[ 5 -3]
 [ 0  8]]
DOT:
[[  4. -11.]
 [  0.  15.]] (2, 2)
[[  4 -11]
 [  0  15]]


#### Задание 3:
Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [8]:
def dot_num(A, num):
    (rows, cols) = np.shape(A)
    return [[A[row][col]*num for col in range(cols)] for row in range(rows)]

In [9]:
A = [[1, 7], [3, -6]]
B = [[0, 5], [2, -1]]
C = [[2, -4], [1, 1]]

S = m_sum(m_sum(dot_num(A, 3), dot_num(B, -2))[0], dot_num(C, 4))[0]
print(S)
print(np.array(A)*3 - np.array(B)*2 + np.array(C)*4)

[[ 11.  -5.]
 [  9. -12.]]
[[ 11  -5]
 [  9 -12]]


#### Задание 4:
Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [10]:
def transpose(A):
    (rows, cols) = np.shape(A)
    return [[A[row][col] for row in range(rows)] for col in range(cols)]

In [11]:
A = [[4, 1], [5, -2], [2, 3]]

In [12]:
A_AT = dot(A, transpose(A))[0]
AT_A = dot(transpose(A), A)[0]
np_A = np.array(A)

print('A * A.T:')
print(A_AT)
print(np_A.dot(np_A.T))
print('A.T * A:')
print(AT_A)
print(np_A.T.dot(np_A))

A * A.T:
[[17. 18. 11.]
 [18. 29.  4.]
 [11.  4. 13.]]
[[17 18 11]
 [18 29  4]
 [11  4 13]]
A.T * A:
[[45.  0.]
 [ 0. 14.]]
[[45  0]
 [ 0 14]]


#### Задание 5:
Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [13]:
def shape(A):
    return len(A), len(A[0])

def can_dot_npfree(A, B):
    return shape(A)[1] == shape(B)[0]

In [14]:
def dot_npfree(A, B):
    if not can_dot_npfree(A, B):
        raise Exception("Cant multiply matrixes with shapes", shape(A), shape(B))
        
    cols, count = shape(A)
    rows = shape(B)[1]
    C = [[0 for col in range(cols)] for row in range(rows)]
    for i in range(cols):
        for j in range(rows):
            C[i][j] = sum([A[i][p]*B[p][j] for p in range(count)])
    return C, (cols, rows)    

In [15]:
A = [[1, -2], [0, 3]]
B = [[4, -1], [0, 5]]

M, m_shape = dot_npfree(A, B)
print(np.array(M))
print('проверка:')
print(np.dot(A,B))

[[  4 -11]
 [  0  15]]
проверка:
[[  4 -11]
 [  0  15]]
