In [10]:
import numpy as np

##### TODO: сделать алгоритм ...чего-то. Уточнить в лекции

In [11]:
def can_dot(A, B):
    return np.shape(A)[1] == np.shape(B)[0]

In [32]:
def dot(A, B):
    if not can_dot(A, B):
        raise Exception("Cant multiply matrixes with shapes", np.shape(A), np.shape(B))
        
    cols, count = np.shape(A)
    rows = np.shape(B)[1]
    C = np.zeros([cols, rows])
    for i in range(cols):
        for j in range(rows):
            C[i][j] = sum([A[i, p]*B[p, j] for p in range(count)])
    return C, (cols, rows)
    

In [37]:
A = np.ones([2,3])
B = np.ones([3,4])

print(np.dot(A, B))

C, c_shape = dot(A, B)
print(C, c_shape)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]] (2, 4)
